### ISSUE TITLE
Emulador Fiscal

### ISSUE THREAD

**Issue by catrielr** [csrocha/fpoc-chrome#1]
En la consola del emulador fiscal veo esto:
n°seq |  Comando                | Descripcion               |  Resultado
81      | Comando Invalido!   | No hay descripcion   |  -ERR: Comando desconocido
82      | Comando Invalido!   | No hay descripcion   |  -ERR: Comando desconocido

Errores de la consola de debug de chrome:

 [SES] Start background login.
background.js:46 [SES] Creating the session.
background.js:69 [SES] Session error. Forget session_id.
extensions::binding:471 chrome.appViewInternal is not available: 'appViewInternal' requires Google Chrome dev channel or newer, but this is the stable channel.
background.js:10 [FP] Pooling for printers
oerp.js:346 [SES] Updating printers.
tools.js:200 [PF] USB found end
2epson_ar.js:1611 EPSON: Constructor
3extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of null
    at onReceive (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:26:50)
epson_ar.js:303 Type  \*  not implemented
extensions::uncaught_exception_handler:8 Error in response to serial.send: RangeError: Offset is outside the bounds of the DataView
    at unpack (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:295:23)
    at chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:435:64
    at chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:408:61
    at Object.callback (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:60:21)
    at send (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:53:23)
    at sendACK (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:408:24)
    at local_callback (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:434:30)
    at receive (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:85:21)
    at chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:92:22
extensions::uncaught_exception_handler:8 Error in response to serial.send: RangeError: Offset is outside the bounds of the DataView
    at unpack (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:298:23)
    at chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:435:64
    at chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:408:61
    at Object.callback (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:60:21)
    at send (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:53:23)
    at sendACK (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:408:24)
    at local_callback (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:434:30)
    at receive (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:85:21)
    at chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:92:22

**Comment by csrocha** [comment]
Catriel,

necesito que des un mejor descripción del problema. Que equipo estás usando, en que momento del proceso ocurre el error. Algo que me ayude a entender y a replicar el error.

Gracias.

**Comment by martinfpas** [comment]
Mismo error con el emulador fiscal. No me muestra impresoras locales.

La impresora emulada por COM2 es la "EPSON TMU220AF/AF II" 

El error que mensiona Catriel en el emulador (Comando Invalido!), solo lo puedo ver si habilito y desabilito la extension y se da Antes de conectar al server. 

Pero cada vez que logueo la extension veo el error que sigue:

 Error in response to serial.connect: TypeError: Cannot read property 'connectionId' of undefined
    at send (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/serial.js:53:38)
    at chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/epson_ar.js:503:36
    at alive (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/serial.js:98:9)
    at command (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/epson_ar.js:494:24)
    at _get_status (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/epson_ar.js:511:13)
    at get_status (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/epson_ar.js:1398:18)
    at chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/tools.js:116:29
    at chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/epson_ar.js:1618:37
    at Object.callback (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/serial.js:40:21)
    at open (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/serial.js:37:23)
    at epson_ar_open (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/epson_ar.js:1618:15)
    at declarePrinter (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/tools.js:114:35)
    at chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/tools.js:207:13
    at chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/async.js:111:13
    at _each (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/async.js:32:24)
extensions::sendRequest:82 Unchecked runtime.lastError while running serial.connect: Failed to connect to the port.
    at open (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/serial.js:37:23)
    at epson_ar_open (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/epson_ar.js:1618:15)
    at declarePrinter (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/tools.js:114:35)
    at chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/tools.js:207:13
    at chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/async.js:111:13
    at _each (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/async.js:32:24)
extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/serial.js:26:50)
epson_ar.js:303 Type  \*  not implemented

**Comment by csrocha** [comment]
Bien, parece que el emuador fiscal no es visible desde chrome.

Por partes:
Type \* not implemented
No es un error. Es respuesta a la finalización de un paquete.

TypeError: Cannot read property 'connectionId' of undefined
at onReceive
(chrome-extension://hgihfepglfkholfnjcekhabghdkgkahb/src/serial.js:26:50)

Es el error. Voy a revisar. Por lo que veo Chrome reconoce parcialmente el
puerto serial virtual.

Como nadie respondió ni indicó, lo digo yo. Esto ocurre en M$ Windows con
el emulador fiscal de impresorasfiscales.com.ar

No se, ni en que versión de windows ni en que versión del emulador.

Cuando prepare el ambiente de test seguramente lo voy a hacer en un windows
vista en un Virtual Box pero no se que versión del emulador. Cuando lo
tenga les aviso. Solo espero que funcione.

**Comment by catrielr** [comment]
Hola Cristian, perdon por la falta de detalles.
Impresora: 
                 Emulador Fiscal (www.impresoras-fiscales.com.ar) 
                 Epson TMU220AF/AF II
Puerto COM: 
                ELTIMA  Virtual Serial Port (COM2)

Windows XP SP3 
Chrome Versión 39.0.2171.95 m
El primer "comando no valido" en la impresora es  cuando se carga el "EPSON: Constructor" 

Despues se detiene aca:

this.onReceive = function(receiveInfo) {
      if (receiveInfo.connectionId === connection.connectionId) {
        var dataView = new Uint8Array(receiveInfo.data);
        buffer = concatBuf(buffer, receiveInfo.data);
      }
    };

---

2extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of null
    at onReceive (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:26:50)
    at onReceive (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:26:50)

---

connection: Object
bitrate: 9600
bufferSize: 4096
connectionId: 12
ctsFlowControl: false
dataBits: "eight"
name: ""
parityBit: "no"
paused: false
persistent: false
receiveTimeout: 0
sendTimeout: 0
stopBits: "one"
**proto**: Object

---

receiveInfo: Object
connectionId: 11
data: ArrayBuffer
byteLength: (...)
**proto**: ArrayBuffer
byteLength: (...)
get byteLength: function byteLength() { [native code] }
constructor: function ArrayBuffer() { [native code] }
slice: function slice() { [native code] }
**proto**: Object
**proto**: Object

---

Despues aparece "Type  \*  not implemented"
en Epson_ar.js
if (['>'].indexOf(types[i]) >= 0) {
            var d = v.getUint8(l++);
        } else

Despues esto:

 Error in response to serial.send: RangeError: Offset is outside the bounds of the DataView
    at unpack (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:295:23)
    at chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:435:64
    at chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:408:61
    at Object.callback (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:60:21)
    at send (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:53:23)
    at sendACK (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:408:24)
    at local_callback (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/epson_ar.js:434:30)
    at receive (chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:85:21)
    at chrome-extension://dpdhliallpdhnnkmhcmdmdecmholihmm/src/serial.js:92:22

aca:
if (['_'].indexOf(types[i]) >= 0) {
            var d = v.getUint8(l++);
        } else

Si queres pongo un teamviewer o algo para que veas en mi pc.
Abrazo
Catriel

**Comment by csrocha** [comment]
Catriel,

descarto que el problema sea de Chrome. Ahora estoy dudando de donde sale el error, si es del ReceiveInfo  o de connection. Hice un branch  (csrocha/fpoc-chrome/tree/issue_1 2bc6d178d520e3dc03514f7251f4923b8b44ec28) donde muestra esos dos valores en la consola. Podrías copiarme la salida de la consola previo al error. Especialmente los mensajes ReceiveInfo y Connection.

Saludos,
Cristian.

**Comment by martinfpas** [comment]
También me paso con esa versión de XP. Es una virtual con Vbox

La versión del emulador es 5.3.14.01

Podrá ser un tema sistema operativo?

**Comment by catrielr** [comment]
Cristian, ahi instala la 0.0.7

var serial = function(device) {
    var connection = null;
    var receive_callback = null;
    var self = this;
    var buffer = new ArrayBuffer();
    var bufferRef = 0;

```
this.device = device;
this.type = 'serial';
```

no se porque devices esta asi:

---

device: Object
path: "COM3"

---

Asi que ambie el port de la impre a COM3, estaba en COM2

---

Ahora quedan asi:

receiveInfo: <not available>
connection: null

---

y aca:

```
this.send = function(data, callback) { 
    var self = this;
    var callback = callback;
    buffer = buffer.slice(bufferRef);
    bufferRef = 0;
    chrome.serial.send(connection.connectionId, data,
            function(res) {
                if (res.error) {
                    res.resultCode = -1;
                } else {
                    res.resultCode = 0;
                }
                callback(res);
            });
```

---

da este error:
 Error in response to serial.connect: TypeError: Cannot read property 'connectionId' of undefined
    at send (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:53:38)
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:503:36
    at alive (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:98:9)
    at command (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:494:24)
    at _get_status (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:511:13)
    at get_status (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:1398:18)
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/tools.js:116:29
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:1618:37
    at Object.callback (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:40:21)
    at open (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:37:23)
    at epson_ar_open (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:1618:15)
    at declarePrinter (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/tools.js:114:35)
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/tools.js:207:13
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/async.js:111:13
    at _each (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/async.js:32:24)
extensions::sendRequest:82 Unchecked runtime.lastError while running serial.connect: Failed to connect to the port.
    at open (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:37:23)
    at epson_ar_open (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:1618:15)
    at declarePrinter (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/tools.js:114:35)
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/tools.js:207:13
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/async.js:111:13
    at _each (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/async.js:32:24)
epson_ar.js:303 Type  \*  not implemented
2extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:26:50)
    at onReceive (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:26:50)
extensions::uncaught_exception_handler:8 Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of undefined
    at onReceive (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:26:50)
extensions::uncaught_exception_handler:8 Error in response to serial.send: RangeError: Offset is outside the bounds of the DataView
    at unpack (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:298:23)
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:435:64
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:408:61
    at Object.callback (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:60:21)
    at send (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:53:23)
    at sendACK (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:408:24)
    at waitResponse.local_callback (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_ar.js:434:30)
    at receive (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:85:21)
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:92:22

---

El "Type \* ..." no lo da mas..

**Comment by csrocha** [comment]
@catrielr actualiza el código con la última versión. Creo que ahora debería funcionar :pray:

**Comment by catrielr** [comment]
si me paro en "self"
en: 

this.send = function(data, callback) { 
        var self = this;
        var callback = callback;
        buffer = buffer.slice(bufferRef);
        bufferRef = 0;
        chrome.serial.send(self.connection.connectionId, data,
                function(res) {
                    if (res.error) {
                        res.resultCode = -1;
                    } else {
                        res.resultCode = 0;
                    }
                    callback(res);
                });

---

me da estos valores:

serial
alive: function (alive_callback, dead_callback) {
close: function (callback) {
connection: undefined
device: Object
onReceive: function (receiveInfo) {
open: function (callback) {
receive: function (callback, count) {
sameDevice: function (device) {
send: function (data, callback) {
type: "serial"
**proto**: serial

queres entrar en mi compu?

**Comment by csrocha** [comment]
El protocolo del emulador de impresoras fiscales de http://www.impresoras-fiscales.com.ar/ es el viejo, Revisión D. en cambio en fpoc-chrome es la Revisión E. Este protocolo funciona con impresoras modelo TM-U220AFII versión 22.01 Demeter. 

Dejo el Issue abierto para cuando tenga la documentación Revisión E poder implementarla.

Ref: http://www.impresoras-fiscales.com.ar/emulador.htm (Nota importante para los usuarios impresora fiscal Epson TM-U220AF)

**Comment by martinfpas** [comment]
Es una lastima, era una buena opción.

Se agradece

**Comment by csrocha** [comment]
Gente, podrían probar si se reconoce la impresora con el emulador fiscal? No debería de funcionar todo, pero si reconocerla. Implementé solo el comando 0x2a, con eso puedo mostrar una impresora con el protocolo viejo. Debería aparecer como epson_d_ar:Modelo/NoSerie

**Comment by catrielr** [comment]
Error in event handler for serial.onReceive: TypeError: Cannot read property 'connectionId' of null
    at onReceive (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:26:50)extensions::uncaught_exception_handler:8 handlerextensions::uncaught_exception_handler:100 exports.handleextensions::event_bindings:384 EventImpl.dispatch_extensions::event_bindings:247 dispatchArgsextensions::event_bindings:256 dispatchEvent
epson_common.js:191 Type  \*  not implemented
tools.js:119 [FP] New printer epson_d_ar://Hera211:PEL0012027
extensions::uncaught_exception_handler:8 Error in response to serial.send: RangeError: Offset is outside the bounds of the DataView
    at unpack (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_common.js:183:17)
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_common.js:236:43
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_common.js:208:66
    at Object.callback (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:60:21)
    at send (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:53:23)
    at sendACK (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_common.js:208:24)
    at local_callback (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_common.js:235:30)
    at receive (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:85:21)
    at chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:92:22extensions::uncaught_exception_handler:8 handlerextensions::uncaught_exception_handler:100 exports.handleextensions::sendRequest:23 safeCallbackApplyextensions::sendRequest:73 handleResponse

**Comment by csrocha** [comment]
Pongo en context. Con Catriel estuvimos viendo el funcionamiento con la
impresora virtual. Avanzamos, sale este error ahora, pero la impresora
virtual pudo reconocer la consulta de estado.

On Tue, Jan 13, 2015 at 12:30 PM, Catriel notifications@github.com wrote:

> Error in event handler for serial.onReceive: TypeError: Cannot read
> property 'connectionId' of null
> at onReceive
> (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:26:50)extensions::uncaught_exception_handler:8
> handlerextensions::uncaught_exception_handler:100
> exports.handleextensions::event_bindings:384
> EventImpl.dispatch_extensions::event_bindings:247
> dispatchArgsextensions::event_bindings:256 dispatchEvent
> epson_common.js:191 Type \* not implemented
> tools.js:119 [FP] New printer epson_d_ar://Hera211:PEL0012027
> extensions::uncaught_exception_handler:8 Error in response to serial.send:
> RangeError: Offset is outside the bounds of the DataView
> at unpack
> (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_common.js:183:17)
> at
> chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_common.js:236:43
> at
> chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_common.js:208:66
> at Object.callback
> (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:60:21)
> at send
> (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:53:23)
> at sendACK
> (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_common.js:208:24)
> at local_callback
> (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/epson_common.js:235:30)
> at receive
> (chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:85:21)
> at
> chrome-extension://cjdieljdmnjhdlfenkdmiogedmlkahlj/src/serial.js:92:22extensions::uncaught_exception_handler:8
> handlerextensions::uncaught_exception_handler:100
> exports.handleextensions::sendRequest:23
> safeCallbackApplyextensions::sendRequest:73 handleResponse
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/csrocha/fpoc-chrome/issues/1#issuecomment-69761681.

## 

Coop. de Trab. Moldeo Interactive Lmt.
Cristian Sebastian Rocha
Consultor Analista.
Bonpland 2363 Of 303
(C1425FWE) CABA, Argentina.
(+54-9-11).6800.0269
http://interactive.moldeo.coop

**Comment by csrocha** [comment]
Revisando encuentro que Chrome no logra capturar los puertos serial de Windows. 

```
    this.open = function(callback) {
        var self = this;
        var callback = callback;
        chrome.serial.connect(device.path, {},
                function(connInfo) {
                  if (connInfo) {
                    connection = connInfo;
                    callback(self);
                  } else {
                    callback();
                  }
                  }
                });
    };
```

Esta función toma el control del serial, pero la función de chrome no devuelve la conexión. Sin ella no se puede hacer nada.

**Comment by catrielr** [comment]
Voy hacer esta prueba, voy a conectar el emulador a un puerto USB, a ver que pasa..

**Comment by martinfpas** [comment]
Yo creo que no se puede conectar el emulador por USB, Pero al menos con la version 0.0.8, a pesar que persisten los mensajes de "Comando Invalido", estaría detectando la impresora. Adjunto una captura.

![c_rocha_fisca_printer_error2](https://cloud.githubusercontent.com/assets/5508133/5777954/f0c1c6ba-9d75-11e4-9d91-0024c5a87f07.png)

**Comment by csrocha** [comment]
@martinfpas , está eligiendo mal el protocolo. Fijate que dice: epson_e_ar y solo funciona el epson_d_ar. Vamos viendo de a poco, por que ese protocolo no está implementado completamente.

**Comment by martinfpas** [comment]
Si, algo leí de lo que habías escrito. Solo lo postie por si aportaba algo la prueba que hice.

Consulta, Con las impresoras reales les esta andando bien?

**Comment by csrocha** [comment]
Martín, te recomiendo que veas la lista de impresoras y su estado. La estoy actualizando cuando hay novedades.

**Comment by csrocha** [comment]
La cierro por el tiempo que pasó.

**Comment by regaby** [comment]
Hola, estoy tratando de conectar la extensión de chrome con el emulador fiscal, pero no logro que me detecte la impresora. Al iniciar la extensión el emulador recibe el mensaje de conexión (Consulta de estado: +OK) y al querer detener cerrar el puerto del emulador sale un warning que no se puede cerrar porque hay una aplicación conectada (adjunto captura)
Versión del emulador: 5.3.14.01
Windows xp sp3 virtualizado

![prueba_emulador](https://user-images.githubusercontent.com/8516488/34443507-62d7766e-eca6-11e7-90cc-dac1869cc2bf.png)

Desde ya agradezco su alguien me puede ayudar con esto
Saludos

**Comment by morrillo** [comment]
no lo pruebes con un emulador. Aca lo desarrollamos con las impresoras reales y funciona. Con emulador no sabemos bien que puede llegar a pasar
