### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'split'

### ISSUE THREAD

**Issue by martinfpas** [csrocha/fpoc-chrome#2]
Hola Cristian,  instale los modulos

odoo_fpoc
l10n_ar_fpoc
l10n_ar_fpoc_pos

y tengo en una virtual de vbox el emulador fiscal con el COM2 virtual.

Fui hasta Configuracion > Fiscal Printer > Crear

ahi trate de darle de alta con los siguientes datos (no vi ningun instructivo, asi que solo deduje los campos)

![c_rocha_fisca_printer_error](https://cloud.githubusercontent.com/assets/5508133/5657601/bdb37ebe-96cf-11e4-9b54-33593c857213.png)

Cuando trato de guardar me da el siguiente error:

2015-01-08 03:32:55,246 2883 ERROR test openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/vagrant/odoo/openerp/http.py", line 524, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/vagrant/odoo/openerp/http.py", line 545, in dispatch
    result = self._call_function(*_self.params)
  File "/vagrant/odoo/openerp/http.py", line 301, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/vagrant/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/vagrant/odoo/openerp/http.py", line 298, in checked_call
    return self.endpoint(_a, *_kw)
  File "/vagrant/odoo/openerp/http.py", line 761, in __call__
    return self.method(_args, *_kw)
  File "/vagrant/odoo/openerp/http.py", line 394, in response_wrap
    response = f(_args, *_kw)
  File "/vagrant/odoo/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/vagrant/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/vagrant/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/vagrant/odoo/openerp/api.py", line 332, in old_api
    result = method(recs, _args, *_kwargs)
  File "/vagrant/odoo/openerp/models.py", line 4007, in create
    record = self.browse(self._create(old_vals))
  File "/vagrant/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/vagrant/odoo/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/vagrant/odoo/openerp/models.py", line 4192, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/vagrant/odoo/openerp/osv/fields.py", line 1384, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/vagrant/odoo/addons/fpoc/epson.py", line 72, in _put_field
    lines = field_value.split('\n')[:len(_footer_lines)]
AttributeError: 'bool' object has no attribute 'split'

Muchas gracias
Saludos
Martin

**Comment by csrocha** [comment]
Martín,

Te dejo el video https://www.youtube.com/watch?v=Ku77eyIPjtw donde vas a poder ver el inicio del uso de la impresora. Aunque es una versión vieja del soft el proceso de instalación es el mismo.

Para quienes no puedan ver el video, la forma correcta de agregar una impresora es usando la opción "Disconnected" y no agregando la impresora desde Crear.

Veo el error y te respondo.

Saludos,
Cristian.

**Comment by csrocha** [comment]
@martinfpas , me acabo de dar cuenta que el issue no corresponde a csrocha/fpoc-chrome sino a csrocha/odoo_fpoc. Podrías copiar el issue? No se puede migrar, por lo que si lo creo yo se va a perder tu colaboración.
