### ISSUE TITLE
No conecta con Odoo v9

### ISSUE THREAD

**Issue by efarias** [csrocha/fpoc-chrome#9]
Hola Cristian, he logrado instalar fpoc en Odoo v9, sin embargo la extensión de Chrome no logra conectarse con el servidor, da el siguiente error:

016-02-29 18:45:26,671 4974 ERROR ? openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 1624, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
2016-02-29 18:45:26,680 4974 INFO ? werkzeug: 192.168.189.100 - - [29/Feb/2016 18:45:26] "GET /web/database/get_list?jsonp=_&id=p1&r=%7B%22params%22%3A%7B%7D%7D HTTP/1.1" 200 -

Saludos!

**Comment by csrocha** [comment]
@efairas, el log que envías está incompleto. Necesitaría las lineas previas.

**Comment by dansanti** [comment]
Hola! es como dice @efarias  aparece ese error, al parecer la llamada para obtener el listado de base de datos lo está provocando : 
https://github.com/csrocha/fpoc-chrome/blob/master/view/status.js#L201

**Comment by dansanti** [comment]
Ok, el problema se da aquí:

1.- Odoo 9 tiene url "web/database/selector" "get_list", fue eliminado como obsoleto
2.- La llamada debe ser estrictamente http, no del tipo json, al pereser se puede entregar un parametro que active el dump json, pero la llamada debe ser http o se debe buscar otro método de obtener el listado de database.
https://github.com/csrocha/fpoc-chrome/blob/f1c3ed1d0af5d202132344e77bfbd1bfdd4d006e/src/oerp.js#L244

**Comment by comtom** [comment]
Confirmo el bug. Me pasa exactamente lo mismo. Creo que @dansanti dio en el clavo, odoo devuelve esa vista como una pagina html en vez de json. Alguien pudo encontrar algun workarround?

Para poder instalar el modulo fpoc en odoo 9 tuve que modificar una vista, mas tarde les hago un pull request.
Gracias!

**Comment by comtom** [comment]
Buenas, he podido integrar esta app con odoo 9. Lo que queda pendiente es reescribir el metodo get_database_list ya que de momento la lista de bases de datos esta "cableada". Por lo que vi, al ejecutar el metodo para obtener la lista de bases de datos solo devuelve XML. Si se introduce el parametro jsonp, devuelve un error 500.
Ejemplo de la llamada: http://localhost:8069/xmlrpc/db
enviado por post con header: Content-type: application/xml
cuerpo:
`<?xml version='1.0'?>
<methodCall>
<methodName>list</methodName>
<params>
</params>
</methodCall>`

Acabo de hacer un pull request para integrar los cambios:
https://github.com/csrocha/fpoc-chrome/pull/12
